#server:
#  port: 8083
#
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/user_management_pro
#    username: root
#    password: Edith@2000
#
#  jpa:
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQLDialect
#    hibernate:
#      ddl-auto: update
##
##  profiles:
##    active: dev
